downgrade archlinux image to solve missing symbol
Build in latest archlinux is failing with:
  /usr/sbin/ld: /usr/lib/libpango-1.0.so:
  undefined reference to `g_once_init_enter_pointer'